### ISSUE TITLE
Suggestion: Make it possible to customize key combination

### ISSUE THREAD

**Issue by erf** [kupospelov/vis-ctags#12]
Hey! Do you think it would be possible to make the default key map customizable or make the commands available so we could map them ourselves? My norwegian keyboard have some problems with the current key combination.

**Comment by kupospelov** [comment]
At the moment this is not really customizable. However, this should be easy to fix. The code could be restructured a little bit to give names to the functions passed to `vis:map` inside the plugin. The action functions then could be exported in a table (e.g. `ctags.actions`) as described in https://www.lua.org/pil/15.2.html.

Once this is done, the user could just unmap any default binding and map the corresponding exported action to any other key combination.

I may not have time to implement this in the near future, so please feel free to create a pull request if you want to see it fixed sooner :)

**Comment by erf** [comment]
I will look into it :)
