### ISSUE TITLE
Suggestion: order of files in vertical menu when listing matches

### ISSUE THREAD

**Issue by erf** [kupospelov/vis-ctags#15]
I noticed when trying out the new vertical menu that in some cases when calling `tselect` a `.c` file came before a `.h`, i wonder if it would make sense to order these so that in these cases `.h` files are ordered before `.c` files?

An example is if you call `tselect` on `view.c` line 70 char 2 (in the `vis` source code), `view.c` comes before `view.h`.

**Comment by kupospelov** [comment]
From what I see, vim works the same way.

I am a bit skeptical about such a feature. This solution would be limited only to C/C++ programs, but there are many more languages supported by ctags.

However, even if we sorted the list using some other criteria, I doubt there would be a preferred order. Ctags is kind of a rudimentary tool, so as a rule we do not have enough information and thus have no idea which menu item is the most relevant.

**Comment by erf** [comment]
You could check for file extension and sort the order just in the case of `.h` or `.cpp` files, it seem to make sense from a UI perspective if you are a C/C++ developer. But i see the case for keeping it simple, and i don't do much C/C++ dev myself, so i will close this :)
