### ISSUE TITLE
Regression for lua versions < 5.3

### ISSUE THREAD

**Issue by mujo-hash** [kupospelov/vis-ctags#16]
It appears that 012f80085218a23ce7d205c0e98e08ab2b00147c added a lua5.3 specific feature, the `//` operator on line 245.

We can compare the arithmetic operators available in 5.3 and in 5.2 to see the change:
[lua 5.3](https://www.lua.org/manual/5.3/manual.html#3.4.1)
[lua 5.2](https://www.lua.org/manual/5.2/manual.html#3.4.1)

As vis still supports older lua versions, I think we should too.

I noticed this error when using vis on a centos system with an older version of lua installed.

**Comment by kupospelov** [comment]
The fix has been merged.
