### ISSUE TITLE
Rename ctags.lua to init.lua

### ISSUE THREAD

**Issue by mujo-hash** [kupospelov/vis-ctags#18]
According to `:help "Lua paths"` in [vis](https://github.com/martanne/vis/wiki/Plugins) if we move ctags.lua to init.lua we can simplify the `require()` line to use this plugin. Other plugins follow this convention, but it's not a big deal either way.

If the file is renamed, we can use `require(vis-ctags)` instead of `require(vis-ctags/ctags)`

**Comment by kupospelov** [comment]
I think this makes sense. I added a warning message though, so that the users of `ctags.lua` should get some guidance on how to update their configuration files.
