### ISSUE TITLE
Go back to previous file?

### ISSUE THREAD

**Issue by timfayz** [kupospelov/vis-ctags#4]
Hello Kostya! :)

I need a hint how to go back to the previous window/file. For now vis (after pressing `Ctrl+]`) jumps to the file as expected but closing previous one with no way switch back. Is it correct behaviour? The README says it should open new window but there is no such :(

Just in case: `vis 0.5` and today's version of `vis-ctags`

**Comment by timfayz** [comment]
Great!

Can I ask off-topic question? How to change the window sizes after the view is splitted (eg creating window using `Ctrl+v`)?

**Comment by kupospelov** [comment]
I have not seen any shortcuts for this in the vis manual, and those for vim do not seem to work either, so probably this is not possible at this point.

Thanks for the feedback, I'll add an example to the paragraph with the ctags options when I update the file next time.

**Comment by timfayz** [comment]
Got it. That's sad.
Thank you anyway and good bye!)

Regards,

*Timur Fayzrakhmanov*
Software engineer at MCST
Kaliningrad, Russia
+79047667076
LinkedIn <http://www.linkedin.com/in/timfayz>

**Comment by erf** [comment]
@timfayz `advanced window management` is a [NON-GOAL](https://github.com/martanne/vis#non-goals) of `vis` and the creator encurrages the use of a third party window manager.

**Comment by timfayz** [comment]
@erf I do not consider changing size of the window as an `advanced` feature. If there were tabs I would agree. Otherwise if there is no such basic thing maybe it's better to drop that feature at all?... ^_^
Anyway thank you for pointing it :)

**Comment by erf** [comment]
@timfayz no problem. you might want to check out [kitty](https://github.com/kovidgoyal/kitty), a really fast terminal emulator which i do think has more advanced window management.
